export const BlogAnalysis = [
  {
    userId: "use UserID",
    blogId: "11232v2324",
    post: {
      title: "Ace your interviews with these 5 steps",
      body: "Leave this... I will auto generate something just for presentation today",
      category: ["career"],
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: "https://i.ibb.co/s3GJtfx/blog-1.png",
    },
    comment: "",
    likes: 2,
    readBy: 0,
    timeFrame: "5 mins",
  },
  {
    userId: "use UserID",
    blogId: "23232t2443",
    post: {
      title: "Workplace Toxicity",
      body: "Leave this... I will auto generate something just for presentation today",
      category: ["career", "start-up"],
      timeFrame: "5 mins",
      image: "https://i.ibb.co/6ydVY2q/blog-2.png",
    },
    comment: "",
    likes: 2,
    readBy: 0,
    timeFrame: "5 mins",
  },
  {
    userId: "",
    blogId: "2323926534",
    post: {
      title: "Let’s Talk About Work, Life and Balance",
      body: "Leave this... I will auto generate something just for presentation today",
      category: ["career", "start-up"],
      timeFrame: "5 mins",
      image: "https://i.ibb.co/HnMSsf6/blog-3.png",
    },
    comment: "",
    likes: 1,
    readBy: 0,
    timeFrame: "5 mins",
  },
  {
    userId: "use UserID",
    blogId: "1098sd76y4",
    post: {
      title: "Working Together To Keep Konectin Safe",
      body: "Leave this... I will auto generate something just for presentation today",
      category: ["start-up"],
      timeFrame: "5 mins",
      image: "https://i.ibb.co/bsf3D1b/blog-4.png",
    },
    comment: "",
    likes: 1,
    readBy: 0,
    timeFrame: "5 mins",
  },
  {
    userId: "use UserID",
    blogId: "1183203jsd",
    post: {
      title: "Three Tips to Excel At Salary Negotiations",
      body: "Leave this... I will auto generate something just for presentation today",
      category: ["career", "soft-skills"],
      timeFrame: "5 mins",
      image: "https://i.ibb.co/mBK5bXD/blog-5.png",
    },
    comment: "",
    likes: 8,
    readBy: 0,
    timeFrame: "5 mins",
  },
  {
    userId: "use UserID",
    blogId: "sjka984y66",
    post: {
      title: "Here’s How To Kickstart Your Career",
      body: "Leave this... I will auto generate something just for presentation today",
      category: ["career"],
      timeFrame: "5 mins",
      image: "https://i.ibb.co/sQMJyS4/blog-6.png",
    },
    comment: "",
    likes: 9,
    readBy: 0,
    timeFrame: "5 mins",
  },
];
