import {
  blog1Image,
  blog2Image,
  blog3Image,
  blog4Image,
  blog5Image,
  blog6Image,
  blog7Image,
  blogImage,
} from "../../../../assets";

export const newBlogData = {
  all: [
    {
      title: "Ace your interviews with these 5 steps",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blogImage,
      source: "/blog",
    },
    {
      title: "Workplace Toxicity",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog1Image,
      source: "/blog",
    },
    {
      title: "Let’s Talk About Work, Life and Balance",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog2Image,
      source: "/blog",
    },
    {
      title: "Working Together To Keep Konectin Safe",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog3Image,
      source: "/blog",
    },
    {
      title: "Three Tips to Excel At Salary Negotiations",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog4Image,
      source: "/blog",
    },
    {
      title: "Here’s How To Kickstart Your Career",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog5Image,
      source: "/blog",
    },
    {
      title: "Here’s How To Kickstart Your Career",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog5Image,
      source: "/blog",
    },
    {
      title: "Three Tips to Excel At Salary Negotiations",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog4Image,
      source: "/blog",
    },
    {
      title: "Let’s Talk About Work, Life and Balance",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog2Image,
      source: "/blog",
    },
    {
      title: "Working Together To Keep Konectin Safe",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog3Image,
      source: "/blog",
    },
    {
      title: "Workplace Toxicity",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog1Image,
      source: "/blog",
    },
    {
      title: "Ace your interviews with these 5 steps",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blogImage,
      source: "/blog",
    },
  ],
  career: [
    {
      title: "Here’s How To Kickstart Your Career",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog5Image,
      source: "/blog",
    },
    {
      title: "Three Tips to Excel At Salary Negotiations",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog4Image,
      source: "/blog",
    },

    {
      title: "Let’s Talk About Work, Life and Balance",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog2Image,
      source: "/blog",
    },
    {
      title: "Working Together To Keep Konectin Safe",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog3Image,
      source: "/blog",
    },
    {
      title: "Workplace Toxicity",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog1Image,
      source: "/blog",
    },
    {
      title: "Ace your interviews with these 5 steps",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blogImage,
      source: "/blog",
    },
  ],
  start_up: [
    {
      title: "Let’s Talk About Work, Life and Balance",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog2Image,
      source: "/blog",
    },
    {
      title: "Working Together To Keep Konectin Safe",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog3Image,
      source: "/blog",
    },
    {
      title: "Workplace Toxicity",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog1Image,
      source: "/blog",
    },
    {
      title: "Ace your interviews with these 5 steps",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blogImage,
      source: "/blog",
    },
  ],
};

export const trendingBlogData = {
  all: [
    {
      title: "Ace your interviews with these 5 steps",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog6Image,
      source: "/blog",
    },
    {
      title: "Workplace Toxicity",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blogImage,
      source: "/blog",
    },
    {
      title: "Let’s Talk About Work, Life and Balance",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog7Image,
      source: "/blog",
    },
    {
      title: "Working Together To Keep Konectin Safe",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog3Image,
      source: "/blog",
    },
    {
      title: "Three Tips to Excel At Salary Negotiations",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog4Image,
      source: "/blog",
    },
    {
      title: "Here’s How To Kickstart Your Career",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog5Image,
      source: "/blog",
    },
  ],
  career: [
    {
      title: "Here’s How To Kickstart Your Career",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog5Image,
      source: "/blog",
    },
    {
      title: "Three Tips to Excel At Salary Negotiations",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog4Image,
      source: "/blog",
    },

    {
      title: "Let’s Talk About Work, Life and Balance",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog2Image,
      source: "/blog",
    },
    {
      title: "Working Together To Keep Konectin Safe",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog3Image,
      source: "/blog",
    },
    {
      title: "Workplace Toxicity",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog1Image,
      source: "/blog",
    },
    {
      title: "Ace your interviews with these 5 steps",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blogImage,
      source: "/blog",
    },
  ],
  start_up: [
    {
      title: "Let’s Talk About Work, Life and Balance",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog2Image,
      source: "/blog",
    },
    {
      title: "Working Together To Keep Konectin Safe",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog3Image,
      source: "/blog",
    },
    {
      title: "Workplace Toxicity",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blog1Image,
      source: "/blog",
    },
    {
      title: "Ace your interviews with these 5 steps",
      publisher: "Konectin",
      timeFrame: "5 mins",
      publishedAt: "01 January 2023",
      image: blogImage,
      source: "/blog",
    },
  ],
};
